travis:
  secure:
    BINSTAR_TOKEN: LCd/hpstDPd25l/7pK8HSaVyiKt9HMb+YS6X5L0IQGG4/ieKVtJljorEyr+ZLZ/xrvNEatXEnB2c5v06ofILPllqj3vLL6N2G3A4kQNoNFi/dWtMSj52QNXe49Q7FbXB0VJ6AdyJf4DQfsELenbOm9i3lIh951lsul4LDHR7YvMwEF4Bf6Yj6bkKGpbmD/DcGbL51gQqw49wh8kYke9TxN7sFxfgbOKC8tig9dzd1s6StYiG0cdqU49pQhPmat1p85fl+MfXQvGq8sMMgRao/gswrCb53K/7w7eJTw3K2MLUwoR7qBdBpCdcXGhtuUpXoe7YJ20Jy3vO2aRV4saCvmQxilZnqwmesv0VpzFzWI5wqfycbGXK3QvTMY6VINeojnQWZmEUCQKHaCD6cShPhfgaDAoC8obTZDAZFWqcJoYLhWNiV8NPrgKnFnmkiXdOYvMotU9gVXn017TKCqdPUeyT11mJcuIPWtteG+Q0pCusf8/kuZis4RByAXoLuDBVSkT5zA/4/dpxWLyoAgW1q3gMKTrN4MimdTDMvTFUDp4wJm07auu3rbal0jY+i0Is8xF2Pcnhh6mQVtlwg+HMlbITJwTboWIoWoF8RSsUaNAJi0zT1JZcgLC/bC7iXdJbc3o4cPoZgHzVSRBOWX9lWEjo9ZaUEyJsfbt/nUB+ilo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
