travis:
  secure:
    BINSTAR_TOKEN: CPO8hBqEDYUQP5W+f5zolwF7GnzgRjplcLN2d1FX3L71guAK/vQ3pwtnXvkiQUxejb3aNSLc7OdXprGQxLDL37IcAgZZ6s+oPeyyA5GMG1Oh4WvipNfgHToJ//NZo6ImxvVZRJ4JUp9bIvQBIWPvouxWryln/74oZylz1CPrzsX2iok/SvkJKVVKkg6e/aG6XZ94Q/tLj5WqtaP2q4AvMy/B9GpWLCy7kLzH1FQOMLq/kfbFBn2OGrr8Y4JGCXQkcytxT1t4GWE23xOk3vwaNC201LGZDNDETAyK3CMYomOFaTpmUCrf5t15DN3auJ+Xq/7HJR1vbHytQjUlVQr+9EHsRu5DEiNZbrJGFoeNhvD6fC2pT/deIyMd2dd+zkVFYiz5AB2kEUSK1Q+nnsMUF8KQZk0/WpDNIkZqwhoZK0uJMVtgUCe1OV6CNLcUwkw8rjG9Q1ZIwdojzrpm8uqs62Ch2Pc3JThRoVUghSNmWMsonlDFwfcsXQir46m/nD8NFsw6dtme6BRh3f4AXO+O40FNdK7nzB9DvuAJ6ZaCo38/74kf6ff/Vs/NJkyvf/lZ86Z4EIzdOh6e4Qx62Yje+CbDQHBdcDPI9DWqrNsF18PU1R8PP+mEz/o3I/mx6JBidC6M0PuyJoKinvczNqzZLZERv4Q4INWFc3K5cZ3wO6k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
